version: "3.0"
services:
  dolphindb:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "dolphindb"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      HOST: "0.0.0.0"
      PORT: "8848"
      USERNAME: "(optional)"
      PASSWORD: "(optional)"
      DB_PATH: "dfs://demo"
      TABLE_NAME: "mytable"
      COLUMNS: "date, temperature, location"
      LABELS: "date, filterTemp, sensorLocation"
      DATE_COLUMN: "date"
    ports:
      - 80:80
